### ISSUE TITLE
仕様策定

### ISSUE THREAD

**Issue by LaFr4nc3** [joken/koibito2019#1]
恋人探しアンケートは次の3つのアプリケーションによって構成する．
- Frontend
- Backend
- Matching

Backend - Matching間のやりとりはファイルまたはDBを用いて行う．
どちらを使用するかは，開発難度の低いほうを使う．

```
+----------+     Enquete Result     +---------+  Enquete Result                Enquete Result   +----------+
|          | ---------------------> |         | ---------------->             ----------------> |          |
| Frontend |                        | Backend |                   [ File/DB ]                   | Matching |
|          | <--------------------- |         | <----------------             <---------------- |          |
+----------+  View/Matching Result  +---------+  Matching Result               Matching Result  +----------+
```

---

#### / トップ画面
タイトル，説明，注意事項を表示する．
締め切り時間前はアンケート画面に，
締め切り時間後はマッチング結果画面に遷移するボタンを設置する．

注意事項の内容は，
ユーザーの識別にCookieを使用していること，
そのためCookieを削除，無効化などされると正常に動作しないこと
を含める．

#### /enquete アンケート画面
アンケートを表示する．
アンケートの内容は，
- 自分の名前
- 自分の性別（選択肢: 不明，男性，女性）
- 自分の年齢
- 相手の性別（選択肢: 不明，男性，女性）
- 相手の年齢の許容範囲（最小値と最大値を訊く）
- 質問（複数個）
とする．

文言は堅苦しくならないようにする．

#### /enquete/finish 回答完了画面
アンケートの送信が完了した旨を表示する．
また，結果発表の時刻を表示する．

#### /result マッチング結果画面
マッチング結果を表示する．

### 技術要件
フレームワークはVue.jsを使用する．
セッション管理にはCookieを使用する．

#### User
|   プロパティ名  |       種類       |                                 説明                                 |
|-----------------|------------------|----------------------------------------------------------------------|
| `id`            | `string`         | ID UUIDv4を使用 セッションIDとしても利用                             |
| `name`          | `string`         | 名前 ニックネーム可                                                  |
| `gender`        | `number`         | 性別 0:不明，1:男，2:女                                              |
| `age`           | `number`         | 年齢                                                                 |
| `partnerId`     | `string or null` | 相手のID マッチングするまでは`null` マッチング相手がいなかったら`""` |
| `partnerGender` | `number`         | 相手の性別 genderと同じ表現で                                        |
| `partnerMinAge` | `number`         | 相手の年齢の許容範囲の最低値                                         |
| `partnerMaxAge` | `number`         | 相手の年齢の許容範囲の最高値                                         |
| `answers`       | `number[]`       | アンケートの回答 5段階評価で そうは思わない:1 ~ そう思う:5           |

Example:
```json
{
  "id": "1b740d58-fbbc-4815-b12a-c5c9c7b17bb5",
  "name": "ほげ ふが太郎",
  "gender": 1,
  "age": 18,
  "partnerId": "",
  "partnerGender": 2,
  "partnerMinAge": 16,
  "partnerMaxAge": 24,
  "answers": [1, 3, 2, 5, 4, 2, 1, 5, 3, 5, 2]
}
```

### URL仕様

`/`配下はFrontendのページを返すようにする．
ただし，`/api`配下はBackendで処理する．

#### POST /api/enquete
アンケートの送信先．
受け付けるリクエストボディはjsonでUserモデルから`id`プロパティを抜いたもの．
受け取ったアンケート結果のバリデーションが通れば，ファイルまたはDBに保存する．

Example:
**Request**
```http
POST /api/enquete HTTP/1.1
Content-Type: application/json

{
  "name": "ほげ ふが太郎",
  "gender": 1,
  "age": 18,
  "partnerGender": 2,
  "partnerMinAge": 16,
  "partnerMaxAge": 24,
  "answers": [1, 3, 2, 5, 4, 2, 1, 5, 3, 5, 2]
}
```

**Response**
成功時
```http
HTTP/1.1 201 Created
```
リクエストがおかしい時（リクエストボディが無い，要素が欠けているなど）
```http
HTTP/1.1 400 Bad Request
```
サーバー側でエラーが発生した時
```http
HTTP/1.1 500 Internal Server Error
```

#### GET /api/result
マッチング結果を返す．
締め切り時間前のアクセスには403を返す．
返すのは，マッチング相手の名前．
いない場合は，404を返す．

Example:
**Request**
```http
GET /api/result HTTP/1.1
Accept: application/json
```

**Response**
成功時
```http
HTTP/1.1 200 OK
Content-Type: application/json

{
  "partnerName": "ほげ ふが子"
}
```
マッチング相手がいない時
```http
HTTP/1.1 404 Not Found
Content-Type: application/json
```
締め切り時間前にアクセスされた時
```http
HTTP/1.1 403 Forbidden
```
サーバー側でエラーが発生した時
```http
HTTP/1.1 500 Internal Server Error
```

### 技術要件
フレームワークはExpress.jsを使用する．
セッション管理にはexpress-sessionを使用する．

### Matching処理
アンケート結果のうち回答をベクトルとして保持する．

すべてのアンケートにforeachで以下の処理を行う．
1. マッチング済みかを確認する． マッチング済みなら処理をスキップする．
2. `partnerGender`と一致する`gender`を持ち，
  かつ，`partnerMinAge`から`partnerMaxAge`の範囲に収まる`age`を持つアンケートを探す．
3. 処理中のアンケートと2で探したアンケート群で回答の近さをベクトルの類似度として算出する．
4. 処理中のアンケート及び一番回答の近いアンケートで互いに，相手の`id`を`partnerId`に保存する．
5. 双方のアンケートの`id`をマッチング済みとして保存する．

**Comment by LaFr4nc3** [comment]
疑問，質問，ツッコミなどお待ちしてます．

**Comment by pasutisu** [comment]
* Vueはもしかすると学習コスト的に初心者にはキツいかもなので、規模的にマイクロめなフレームワークでも良いかも
* Cookieの代わりにLocal Storageでもいいかも
* DBはつかったりする？
